version: '1.1'

services:
  ttv-frontend:
    build: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules


  ttv-backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
        - ./backend:/app/backend
    depends_on:
        - mysql
    environment:
      PORT: 8080
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}

  mysql:
    image: mysql:latest
    ports:
      - 3307:3307
    volumes:
      - db-data1:/var/lib/mysql
      - ./backend/src/models/db.sql:/docker-entrypoint-initdb.d/db.sql
    hostname: ${DB_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}


volumes:
  db-data1:
    driver: local